# Generated by Django 2.2.2 on 2020-04-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birh',
            new_name='date_of_birth',
        ),
    ]
