# Generated by Django 2.2.2 on 2020-04-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0002_auto_20200416_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Номер паспорта',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
