# Generated by Django 2.2.2 on 2020-04-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0003_profile_номер паспорта'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Серия паспорта',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
