# Generated by Django 2.2.2 on 2020-04-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0004_profile_серия паспорта'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Город',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Дом',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='Квартира',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='Улица',
            field=models.CharField(default='', max_length=100),
        ),
    ]
