# Generated by Django 2.2.2 on 2020-04-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0005_auto_20200418_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Номер телефона',
            field=models.CharField(default='', max_length=11),
        ),
    ]
