# Generated by Django 2.2.2 on 2020-04-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0006_profile_номер телефона'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x040B7550>', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Имя',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x040B7510>', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='Фамилия',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x040B7530>', max_length=100),
        ),
    ]
