# Generated by Django 2.2.2 on 2020-04-19 07:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0007_auto_20200419_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Фамилия',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x04826530>', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Имя',
            field=models.CharField(default=django.contrib.auth.models.AbstractUser.get_full_name, max_length=100),
        ),
    ]
