# Generated by Django 2.2.2 on 2020-04-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0008_auto_20200419_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Имя',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
