# Generated by Django 2.2.2 on 2020-04-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0009_auto_20200419_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Отчество',
            field=models.CharField(default='Отчество', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Фамилия',
            field=models.CharField(default='Фамилия', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Имя',
            field=models.CharField(default='Имя', max_length=100, null=True),
        ),
    ]
