# Generated by Django 2.2.2 on 2020-04-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0010_auto_20200419_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='Дата рождения',
        ),
    ]
