# Generated by Django 2.2.2 on 2020-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0011_auto_20200419_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Фамилия',
        ),
        migrations.AddField(
            model_name='profile',
            name='Дата выдачи паспорта',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Место выдачи паспорта',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Отчество',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
