# Generated by Django 2.2.2 on 2020-04-20 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_account', '0012_auto_20200420_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Краткое название проблемы', models.CharField(max_length=100)),
                ('Отрасль права', models.CharField(blank=True, choices=[('КП', 'Конституционное право'), ('АП', 'Административное право'), ('ГП', 'Гражданское право'), ('УП', 'Уголовное право'), ('ГПП', 'Гражданское процессуальное право'), ('АПП', 'Арбитражное процессуальное право'), ('УПП', 'Уголовно-процессуальное право'), ('УИП', 'Уголовно-исполнительное право'), ('ФП', 'Финансовое право'), ('ТП', 'Трудовое право'), ('ЗП', 'Земельное право')], max_length=100, null=True)),
                ('Заявка', models.TextField()),
                ('Время создания заявки', models.DateTimeField(auto_now_add=True)),
                ('Время принятия заявки', models.DateTimeField(blank=True, null=True)),
                ('Время размещения заявки', models.DateTimeField(blank=True, null=True)),
                ('Время первого ответа на заявку', models.DateTimeField(blank=True, null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
