# Generated by Django 2.2.2 on 2020-04-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0013_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client_account.Profile'),
        ),
    ]
