# Generated by Django 2.2.2 on 2020-04-21 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0014_auto_20200421_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
