# Generated by Django 2.2.2 on 2020-04-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0016_auto_20200421_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_account.Profile'),
        ),
    ]
