# Generated by Django 2.2.2 on 2020-05-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0017_auto_20200426_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='Краткое название проблемы',
        ),
        migrations.AddField(
            model_name='applications',
            name='tag',
            field=models.CharField(default='', max_length=100, verbose_name='Краткое название проблемы'),
        ),
    ]
