# Generated by Django 2.2.2 on 2020-05-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0018_auto_20200502_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='Время первого ответа на заявку',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='Время принятия заявки',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='Время размещения заявки',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='Время создания заявки',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='Заявка',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='Отрасль права',
        ),
        migrations.AddField(
            model_name='applications',
            name='application',
            field=models.TextField(default='', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='applications',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('КП', 'Конституционное право'), ('АП', 'Административное право'), ('ГП', 'Гражданское право'), ('УП', 'Уголовное право'), ('ГПП', 'Гражданское процессуальное право'), ('АПП', 'Арбитражное процессуальное право'), ('УПП', 'Уголовно-процессуальное право'), ('УИП', 'Уголовно-исполнительное право'), ('ФП', 'Финансовое право'), ('ТП', 'Трудовое право'), ('ЗП', 'Земельное право')], max_length=100, null=True, verbose_name='Отрасль права'),
        ),
        migrations.AddField(
            model_name='applications',
            name='time_of_application_accept',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время принятия заявки'),
        ),
        migrations.AddField(
            model_name='applications',
            name='time_of_application_creature',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания заявки'),
        ),
        migrations.AddField(
            model_name='applications',
            name='time_of_application_placing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время размещения заявки'),
        ),
        migrations.AddField(
            model_name='applications',
            name='time_of_first_response',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время первого ответа на заявку'),
        ),
    ]
