# Generated by Django 2.2.2 on 2020-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0020_auto_20200516_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status_of_application',
            field=models.CharField(choices=[('Находится в обработке', 'Находится в обработке'), ('Идут торги', 'Идут торги'), ('Ожидание решения', 'Ожидание решения'), ('Заключен договор', 'Заключен договор'), ('Отказано в договоре', 'Отказано в договоре'), ('Заявка откланена', 'Заявка откланена')], default='Находится в обработке', max_length=100, verbose_name='Статус заявки'),
        ),
    ]
