# Generated by Django 2.2.2 on 2020-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0021_applications_status_of_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='number_of_application',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер заявки'),
        ),
    ]
