# Generated by Django 2.2.2 on 2020-08-03 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_account', '0023_auto_20200712_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='id_of_application',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Город',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Дом',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Номер телефона',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Улица',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Наименование организации', models.CharField(default='Наименование организации', max_length=100, null=True)),
                ('Имя генерального директора', models.CharField(default='Имя', max_length=100, null=True)),
                ('Фамилия генерального директора', models.CharField(default='Фамилия', max_length=100, null=True)),
                ('Отчество генерального директора', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Основной государственный регистрационный номер', models.IntegerField(blank=True, null=True)),
                ('Организационно-правовая форма', models.CharField(blank=True, max_length=100, null=True)),
                ('Идентификационный номер налогоплательщика', models.CharField(blank=True, max_length=100, null=True)),
                ('Учредительный документ', models.CharField(blank=True, max_length=100, null=True)),
                ('Код причины постановки на учет', models.IntegerField(blank=True, null=True)),
                ('Дата утверждения учредительного договора', models.DateField(blank=True, null=True)),
                ('Юридический адрес', models.CharField(blank=True, max_length=200, null=True)),
                ('Фактический адрес', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('Номер телефона', models.CharField(default='', max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Отчество', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Основной государственный регистрационный номер ИП', models.IntegerField(blank=True, null=True)),
                ('Идентификационный номер налогоплательщика', models.CharField(blank=True, max_length=100, null=True)),
                ('Номер свидетельства о постановке на учет', models.IntegerField(blank=True, null=True)),
                ('Дата видетельства о постановке на учет', models.DateField(blank=True, null=True)),
                ('Адрес регистрации', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('Номер телефона', models.CharField(default='', max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
