# Generated by Django 2.2.2 on 2020-08-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0024_auto_20200803_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='Учредительный документ',
            field=models.CharField(blank=True, choices=[('Устав', 'Устав'), ('Типовой устав', 'Типовой устав'), ('Учредительный договор', 'Учредительный договор')], max_length=100, null=True),
        ),
    ]
