# Generated by Django 2.2.2 on 2020-08-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0025_auto_20200807_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='is_legal_entity_profile',
            field=models.BooleanField(default=False),
        ),
    ]
