# Generated by Django 2.2.2 on 2020-08-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0026_legalentity_is_legal_entity_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualentrepreneur',
            old_name='Дата видетельства о постановке на учет',
            new_name='Дата свидетельства о постановке на учет',
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='is_individual_entrepreneur_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_natural_person_profile',
            field=models.BooleanField(default=False),
        ),
    ]
