# Generated by Django 2.2.2 on 2020-08-22 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_account', '0027_auto_20200809_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_natural_person_profile', models.BooleanField(default=False)),
                ('Имя', models.CharField(blank=True, max_length=100, null=True)),
                ('Фамилия', models.CharField(blank=True, max_length=100, null=True)),
                ('Отчество', models.CharField(blank=True, max_length=100, null=True)),
                ('Номер паспорта', models.IntegerField(blank=True, null=True)),
                ('Серия паспорта', models.IntegerField(blank=True, null=True)),
                ('Место выдачи паспорта', models.CharField(blank=True, max_length=150, null=True)),
                ('Дата выдачи паспорта', models.DateField(blank=True, null=True)),
                ('Город', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Улица', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Дом', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('Квартира', models.CharField(blank=True, default='', max_length=10)),
                ('Дата рождения', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('Номер телефона', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='Имя',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='Фамилия',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_account.NaturalPerson'),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='Отчество',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
