# Generated by Django 2.2.2 on 2020-08-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0028_auto_20200822_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
