# Generated by Django 2.2.2 on 2020-08-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0029_auto_20200822_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=100, verbose_name='Краткое название проблемы')),
                ('area_of_law', models.CharField(blank=True, choices=[('Конституционное право', 'Конституционное право'), ('Административное право', 'Административное право'), ('Гражданское право', 'Гражданское право'), ('Уголовное право', 'Уголовное право'), ('Гражданское процессуальное право', 'Гражданское процессуальное право'), ('Арбитражное процессуальное право', 'Арбитражное процессуальное право'), ('Уголовно-процессуальное право', 'Уголовно-процессуальное право'), ('Уголовно-исполнительное право', 'Уголовно-исполнительное право'), ('Финансовое право', 'Финансовое право'), ('Трудовое право', 'Трудовое право'), ('Земельное право', 'Земельное право')], max_length=100, null=True, verbose_name='Отрасль права')),
                ('application', models.TextField(default='', verbose_name='Заявка')),
                ('status_of_application', models.CharField(choices=[('Находится в обработке', 'Находится в обработке'), ('Идут торги', 'Идут торги'), ('Ожидание решения', 'Ожидание решения'), ('Заключен договор', 'Заключен договор'), ('Отказано в договоре', 'Отказано в договоре'), ('Заявка откланена', 'Заявка откланена')], default='Находится в обработке', max_length=100, verbose_name='Статус заявки')),
                ('time_of_application_creature', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания заявки')),
                ('time_of_application_accept', models.DateTimeField(blank=True, null=True, verbose_name='Время принятия заявки')),
                ('time_of_application_placing', models.DateTimeField(blank=True, null=True, verbose_name='Время размещения заявки')),
                ('time_of_first_response', models.DateTimeField(blank=True, null=True, verbose_name='Время первого ответа на заявку')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_account.NaturalPerson')),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
