# Generated by Django 2.2.2 on 2020-08-30 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0030_auto_20200823_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
