# Generated by Django 2.2.2 on 2020-09-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0031_auto_20200830_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='Номер телефона',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
