# Generated by Django 2.2.2 on 2020-09-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0032_auto_20200902_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naturalperson',
            name='Город',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Дата выдачи паспорта',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Дата рождения',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Дом',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Квартира',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Место выдачи паспорта',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Номер паспорта',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Номер телефона',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Отчество',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Серия паспорта',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Улица',
        ),
        migrations.RemoveField(
            model_name='naturalperson',
            name='Фамилия',
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='flat',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='home',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='passport_data_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='passport_data_series',
            field=models.IntegerField(blank=True, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='place_of_passport_issuance',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Место выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='street',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Улица'),
        ),
    ]
