# Generated by Django 2.2.2 on 2020-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0033_auto_20200915_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
