# Generated by Django 2.2.2 on 2020-09-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_account', '0034_auto_20200915_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='Адрес регистрации',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='Дата свидетельства о постановке на учет',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='Идентификационный номер налогоплательщика',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='Номер свидетельства о постановке на учет',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='Номер телефона',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='Основной государственный регистрационный номер ИП',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='Отчество',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='Фамилия',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Дата утверждения учредительного договора',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Идентификационный номер налогоплательщика',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Имя генерального директора',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Код причины постановки на учет',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Наименование организации',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Номер телефона',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Организационно-правовая форма',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Основной государственный регистрационный номер',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Отчество генерального директора',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Учредительный документ',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Фактический адрес',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Фамилия генерального директора',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='Юридический адрес',
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='Date_of_approval_of_the_registration_certificate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата свидетельства о постановке на учет'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='main_state_registration_number_individual_entrepreneur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Основной государственный регистрационный номер ИП'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='number_of_the_registration_certificate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер свидетельства о постановке на учет'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='registration_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='taxpayer_identification_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификационный номер налогоплательщика'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='Date_of_approval_of_the_constituent_document',
            field=models.DateField(blank=True, null=True, verbose_name='Дата утверждения учредительного договора'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='actual_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='code_of_the_reason_for_registration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код причины постановки на учет'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='constituent_document',
            field=models.CharField(blank=True, choices=[('Устав', 'Устав'), ('Типовой устав', 'Типовой устав'), ('Учредительный договор', 'Учредительный договор')], max_length=100, null=True, verbose_name='Учредительный документ'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='firstname_general_manager',
            field=models.CharField(default='Имя', max_length=100, null=True, verbose_name='Имя генерального директора'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='lastname_general_manager',
            field=models.CharField(default='Фамилия', max_length=100, null=True, verbose_name='Фамилия генерального директора'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='legal_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='main_state_registration_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Основной государственный регистрационный номер'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='name_of_the_organization',
            field=models.CharField(default='Наименование организации', max_length=100, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='organizational_and_legal_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='patronymic_general_manager',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Отчество генерального директора'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='phone_number',
            field=models.CharField(default='', max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='taxpayer_identification_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификационный номер налогоплательщика'),
        ),
    ]
