# Generated by Django 2.2.2 on 2020-09-02 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Краткое название проблемы', models.CharField(default='', max_length=100)),
                ('Отрасль права', models.CharField(blank=True, choices=[('Конституционное право', 'Конституционное право'), ('Административное право', 'Административное право'), ('Гражданское право', 'Гражданское право'), ('Уголовное право', 'Уголовное право'), ('Гражданское процессуальное право', 'Гражданское процессуальное право'), ('Арбитражное процессуальное право', 'Арбитражное процессуальное право'), ('Уголовно-процессуальное право', 'Уголовно-процессуальное право'), ('Уголовно-исполнительное право', 'Уголовно-исполнительное право'), ('Финансовое право', 'Финансовое право'), ('Трудовое право', 'Трудовое право'), ('Земельное право', 'Земельное право')], max_length=100, null=True)),
                ('Заявка', models.TextField(default='')),
                ('Статус заявки', models.CharField(choices=[('Находится в обработке', 'Находится в обработке'), ('Идут торги', 'Идут торги'), ('Ожидание решения', 'Ожидание решения'), ('Заключен договор', 'Заключен договор'), ('Отказано в договоре', 'Отказано в договоре'), ('Заявка откланена', 'Заявка откланена')], default='Находится в обработке', max_length=100)),
                ('Территория размещения заявки', models.CharField(blank=True, max_length=100, null=True)),
                ('Текущая цена заявки', models.CharField(blank=True, max_length=10, null=True)),
                ('Время создания заявки', models.DateTimeField(auto_now_add=True, null=True)),
                ('Время принятия заявки', models.DateTimeField(blank=True, null=True)),
                ('Время размещения заявки', models.DateTimeField(blank=True, null=True)),
                ('Время первого ответа на заявку', models.DateTimeField(blank=True, null=True)),
                ('Автор', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('Исполнитель', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
