# Generated by Django 2.2.2 on 2020-09-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_auto_20200914_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Автор',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Время первого ответа на заявку',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Время принятия заявки',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Время размещения заявки',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Время создания заявки',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Заявка',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Исполнитель',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Краткое название проблемы',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Отрасль права',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Статус заявки',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Текущая цена заявки',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Территория размещения заявки',
        ),
        migrations.AddField(
            model_name='application',
            name='application_text',
            field=models.TextField(default='', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='application',
            name='area_of_law',
            field=models.CharField(blank=True, choices=[('Конституционное право', 'Конституционное право'), ('Административное право', 'Административное право'), ('Гражданское право', 'Гражданское право'), ('Уголовное право', 'Уголовное право'), ('Гражданское процессуальное право', 'Гражданское процессуальное право'), ('Арбитражное процессуальное право', 'Арбитражное процессуальное право'), ('Уголовно-процессуальное право', 'Уголовно-процессуальное право'), ('Уголовно-исполнительное право', 'Уголовно-исполнительное право'), ('Финансовое право', 'Финансовое право'), ('Трудовое право', 'Трудовое право'), ('Земельное право', 'Земельное право')], max_length=100, null=True, verbose_name='Отрасль права'),
        ),
        migrations.AddField(
            model_name='application',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='application',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_application_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Текущая цена заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='status_of_application',
            field=models.CharField(choices=[('Находится в обработке', 'Находится в обработке'), ('Идут торги', 'Идут торги'), ('Ожидание решения', 'Ожидание решения'), ('Заключен договор', 'Заключен договор'), ('Отказано в договоре', 'Отказано в договоре'), ('Заявка откланена', 'Заявка откланена')], default='Находится в обработке', max_length=100, verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='tag',
            field=models.CharField(default='', max_length=100, verbose_name='Краткое название проблемы'),
        ),
        migrations.AddField(
            model_name='application',
            name='territory_of_the_host_application',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Территория размещения заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='time_of_application_accept',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время принятия заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='time_of_application_creature',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='time_of_application_placing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время размещения заявки'),
        ),
        migrations.AddField(
            model_name='application',
            name='time_of_first_response',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время первого ответа на заявку'),
        ),
    ]
