# Generated by Django 2.2.2 on 2020-05-16 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Law_firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_law_firm', models.CharField(max_length=100, verbose_name='Название фирмы')),
                ('firstname_general_manager', models.CharField(max_length=100, verbose_name='Имя генерального директора')),
                ('lastname_general_manager', models.CharField(max_length=100, verbose_name='Фамилия генерального директора')),
                ('patronymic_general_manager', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Отчество генерального директора')),
                ('passport_data_number', models.IntegerField(blank=True, null=True, verbose_name='Номер паспорта')),
                ('Серия паспорта', models.IntegerField(blank=True, null=True)),
                ('place_of_passport_issuance', models.CharField(blank=True, max_length=150, null=True, verbose_name='Место выдачи паспорта')),
                ('date_of_approval_of_the_constituent_document', models.DateField(blank=True, null=True, verbose_name='Дата утверждения учредительного документа')),
                ('Organizational_and_legal_form', models.CharField(blank=True, choices=[('Конституционное право', 'Конституционное право'), ('Административное право', 'Административное право'), ('Гражданское право', 'Гражданское право'), ('Уголовное право', 'Уголовное право'), ('Гражданское процессуальное право', 'Гражданское процессуальное право'), ('Арбитражное процессуальное право', 'Арбитражное процессуальное право'), ('Уголовно-процессуальное право', 'Уголовно-процессуальное право'), ('Уголовно-исполнительное право', 'Уголовно-исполнительное право'), ('Финансовое право', 'Финансовое право'), ('Трудовое право', 'Трудовое право'), ('Земельное право', 'Земельное право')], max_length=100, null=True, verbose_name='Организационно-правовая форма')),
                ('Город', models.CharField(default='', max_length=100)),
                ('Улица', models.CharField(default='', max_length=100)),
                ('Дом', models.CharField(default='', max_length=10)),
                ('Квартира', models.CharField(blank=True, default='', max_length=10)),
                ('Дата рождения', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('Номер телефона', models.CharField(default='', max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
