# Generated by Django 2.2.2 on 2020-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law_firm',
            name='Дата рождения',
        ),
        migrations.RemoveField(
            model_name='law_firm',
            name='Квартира',
        ),
        migrations.AddField(
            model_name='law_firm',
            name='main_state_registration_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Основной государственный регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='law_firm',
            name='Organizational_and_legal_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Организационно-правовая форма'),
        ),
    ]
