# Generated by Django 2.2.2 on 2020-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_account', '0003_auto_20200822_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='Имя',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='Фамилия',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='Имя',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='Фамилия',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='individualentrepreneurlawyer',
            name='Отчество',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='Номер телефона',
            field=models.CharField(blank=True, default='', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='memberofthebarchamber',
            name='Отчество',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
