# Generated by Django 2.2.2 on 2020-09-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_account', '0004_auto_20200822_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Банковский индификационный код',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Все отрасли права',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Гражданское право',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Дата совершения доверенности',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Жилищное право',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Идентификационный номер налогоплательщика',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Имя директора филиала',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Код причины постановки на учет',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Муниципальное право',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Наименование головной организации',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Наименование филиала',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Налоговое право',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Номер телефона филиала',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Обслуживающий банк',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Опыт в гражданском праве',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Опыт в жилищном праве',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Опыт в муниципальном праве',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Опыт в налоговом праве',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Опыт в семейном праве',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Опыт в трудовом праве',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Опыт в уголовном праве',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Основной государственный регистрационный номер',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Отчество директора филиала',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Расчетный счет',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Семейное право',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Трудовое право',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Уголовное право',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Фактический адрес филиала',
        ),
        migrations.RemoveField(
            model_name='branchlawfirm',
            name='Фамилия директора филиала',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Адресс офисного помещения',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Адресс регистрации ИП',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Банковский индификационный код',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Все отрасли права',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Гражданское право',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Дата свидетельства о постановке на учет',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Жилищное право',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Идентификационный номер налогоплательщика',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Муниципальное право',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Наличие офисного помещения',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Наличие работников',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Налоговое право',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Номер свидетельства о постановке на учет',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Номер телефона',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Обслуживающий банк',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Опыт в гражданском праве',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Опыт в жилищном праве',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Опыт в муниципальном праве',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Опыт в налоговом праве',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Опыт в семейном праве',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Опыт в трудовом праве',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Опыт в уголовном праве',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Основной государственный регистрационный номер ИП',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Отчество',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Расчетный счет',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Семейное право',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Трудовое право',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Уголовное право',
        ),
        migrations.RemoveField(
            model_name='individualentrepreneurlawyer',
            name='Фамилия',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Банковский индификационный код',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Все отрасли права',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Гражданское право',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Дата утверждения учредительного документа',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Жилищное право',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Идентификационный номер налогоплательщика',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Имя генерального директора',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Код причины постановки на учет',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Муниципальное право',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Название фирмы',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Налоговое право',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Номер телефона',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Обслуживающий банк',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Опыт в гражданском праве',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Опыт в жилищном праве',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Опыт в муниципальном праве',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Опыт в налоговом праве',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Опыт в семейном праве',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Опыт в трудовом праве',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Опыт в уголовном праве',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Организационно-правовая форма',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Основной государственный регистрационный номер',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Отчество генерального директора',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Расчетный счет',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Семейное право',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Трудовое право',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Уголовное право',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Учредительный документ',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Фактический адрес',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Фамилия генерального директора',
        ),
        migrations.RemoveField(
            model_name='lawfirm',
            name='Юридический адрес',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Адвокатская палата',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Адресс офисного помещения',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Банковский индификационный код',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Все отрасли права',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Гражданское право',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Дата выдачи удостоверения',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Жилищное право',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Муниципальное право',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Наименование адвокатского образования',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Наличие офисного помещения',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Налоговое право',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Номер телефона',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Номер удостоверения',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Обслуживающий банк',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Опыт в гражданском праве',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Опыт в жилищном праве',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Опыт в муниципальном праве',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Опыт в налоговом праве',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Опыт в семейном праве',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Опыт в трудовом праве',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Опыт в уголовном праве',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Орган, выдавший удостоверение',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Отчество',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Расчетный счет',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Регистрационный номер',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Семейное право',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Трудовое право',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Уголовное право',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Фамилия',
        ),
        migrations.RemoveField(
            model_name='memberofthebarchamber',
            name='Член адвокатского образования',
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='actual_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фактический адрес филиала'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='all_branches_of_law',
            field=models.BooleanField(default=False, verbose_name='Все отрасли права'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='bank_identification_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Банковский индификационный код'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='civil_law',
            field=models.BooleanField(default=False, verbose_name='Гражданское право'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='code_of_the_reason_for_registration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Код причины постановки на учет'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='criminal_law',
            field=models.BooleanField(default=False, verbose_name='Уголовное право'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='date_of_the_power_of_attorney',
            field=models.DateField(blank=True, null=True, verbose_name='Дата совершения доверенности'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='experience_in_civil_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в гражданском праве'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='experience_in_criminal_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в уголовном праве'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='experience_in_family_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в семейном праве'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='experience_in_housing_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в жилищном праве'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='experience_in_labour_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в трудовом праве'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='experience_in_municipal_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в муниципальном праве'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='experience_in_tax_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в налоговом праве'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='family_law',
            field=models.BooleanField(default=False, verbose_name='Семейное право'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='firstname_general_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя директора филиала'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='housing_law',
            field=models.BooleanField(default=False, verbose_name='Жилищное право'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='labour_law',
            field=models.BooleanField(default=False, verbose_name='Трудовое право'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='lastname_general_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия директора филиала'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='main_state_registration_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Основной государственный регистрационный номер'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='municipal_law',
            field=models.BooleanField(default=False, verbose_name='Муниципальное право'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='name_branch_law_firm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование филиала'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='name_main_law_firm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование головной организации'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='patronymic_general_manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество директора филиала'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='payment_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона филиала'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='servicing_bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Обслуживающий банк'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='tax_law',
            field=models.BooleanField(default=False, verbose_name='Налоговое право'),
        ),
        migrations.AddField(
            model_name='branchlawfirm',
            name='taxpayer_identification_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификационный номер налогоплательщика'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='Date_of_approval_of_the_registration_certificate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата свидетельства о постановке на учет'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='address_of_registration_of_an_individual_entrepreneur',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс регистрации ИП'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='address_office_space',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс офисного помещения'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='all_branches_of_law',
            field=models.BooleanField(default=False, verbose_name='Все отрасли права'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='availability_of_employees',
            field=models.BooleanField(default=False, verbose_name='Наличие работников'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='availability_of_office_space',
            field=models.BooleanField(default=False, verbose_name='Наличие офисного помещения'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='bank_identification_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Банковский индификационный код'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='civil_law',
            field=models.BooleanField(default=False, verbose_name='Гражданское право'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='criminal_law',
            field=models.BooleanField(default=False, verbose_name='Уголовное право'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='experience_in_civil_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в гражданском праве'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='experience_in_criminal_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в уголовном праве'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='experience_in_family_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в семейном праве'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='experience_in_housing_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в жилищном праве'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='experience_in_labour_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в трудовом праве'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='experience_in_municipal_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в муниципальном праве'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='experience_in_tax_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в налоговом праве'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='family_law',
            field=models.BooleanField(default=False, verbose_name='Семейное право'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='housing_law',
            field=models.BooleanField(default=False, verbose_name='Жилищное право'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='labour_law',
            field=models.BooleanField(default=False, verbose_name='Трудовое право'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='main_state_registration_number_individual_entrepreneur',
            field=models.IntegerField(blank=True, null=True, verbose_name='Основной государственный регистрационный номер ИП'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='municipal_law',
            field=models.BooleanField(default=False, verbose_name='Муниципальное право'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='number_of_the_registration_certificate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер свидетельства о постановке на учет'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='payment_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='servicing_bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Обслуживающий банк'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='tax_law',
            field=models.BooleanField(default=False, verbose_name='Налоговое право'),
        ),
        migrations.AddField(
            model_name='individualentrepreneurlawyer',
            name='taxpayer_identification_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификационный номер налогоплательщика'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='actual_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='all_branches_of_law',
            field=models.BooleanField(default=False, verbose_name='Все отрасли права'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='bank_identification_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Банковский индификационный код'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='civil_law',
            field=models.BooleanField(default=False, verbose_name='Гражданское право'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='code_of_the_reason_for_registration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Код причины постановки на учет'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='constituent_document',
            field=models.CharField(blank=True, choices=[('Устав', 'Устав'), ('Типовой устав', 'Типовой устав'), ('Учредительный договор', 'Учредительный договор')], max_length=100, null=True, verbose_name='Учредительный документ'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='criminal_law',
            field=models.BooleanField(default=False, verbose_name='Уголовное право'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='date_of_approval_of_the_constituent_document',
            field=models.DateField(blank=True, null=True, verbose_name='Дата утверждения учредительного документа'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='experience_in_civil_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в гражданском праве'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='experience_in_criminal_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в уголовном праве'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='experience_in_family_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в семейном праве'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='experience_in_housing_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в жилищном праве'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='experience_in_labour_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в трудовом праве'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='experience_in_municipal_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в муниципальном праве'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='experience_in_tax_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в налоговом праве'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='family_law',
            field=models.BooleanField(default=False, verbose_name='Семейное право'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='firstname_general_manager',
            field=models.CharField(default='', max_length=100, verbose_name='Имя генерального директора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='housing_law',
            field=models.BooleanField(default=False, verbose_name='Жилищное право'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='labour_law',
            field=models.BooleanField(default=False, verbose_name='Трудовое право'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='lastname_general_manager',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия генерального директора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='legal_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='main_state_registration_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Основной государственный регистрационный номер'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='municipal_law',
            field=models.BooleanField(default=False, verbose_name='Муниципальное право'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='name_law_firm',
            field=models.CharField(default='', max_length=100, verbose_name='Название фирмы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='organizational_and_legal_form',
            field=models.CharField(default='', max_length=100, verbose_name='Организационно-правовая форма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='patronymic_general_manager',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Отчество генерального директора'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='payment_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='servicing_bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Обслуживающий банк'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='tax_law',
            field=models.BooleanField(default=False, verbose_name='Налоговое право'),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='taxpayer_identification_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификационный номер налогоплательщика'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адресс офисного помещения'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='all_branches_of_law',
            field=models.BooleanField(default=False, verbose_name='Все отрасли права'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='authority_that_issued_the_certificate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Орган, выдавший удостоверение'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='availability_of_office_space',
            field=models.BooleanField(default=False, verbose_name='Наличие офисного помещения'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='bank_identification_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Банковский индификационный код'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='bar_association',
            field=models.CharField(blank=True, choices=[('Адвокатский кабинет', 'Адвокатский кабинет'), ('Адвокатская коллегия', 'Адвокатская коллегия'), ('Адвокатское бюро', 'Адвокатское бюро')], max_length=100, null=True, verbose_name='Член адвокатского образования'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='bar_chamber',
            field=models.CharField(blank=True, choices=[('Адвокатская палата Амурской области', 'Адвокатская палата Амурской области'), ('Адвокатская палата Еврейской автономной области', 'Адвокатская палата Еврейской автономной области'), ('Адвокатская палата Камчатского края', 'Адвокатская палата Камчатского края'), ('Адвокатская палата Магаданской области', 'Адвокатская палата Магаданской области'), ('Адвокатская палата Приморского края', 'Адвокатская палата Приморского края'), ('Адвокатская палата Республики Саха (Якутия)', 'Адвокатская палата Республики Саха (Якутия)'), ('Адвокатская палата Сахалинской области', 'Адвокатская палата Сахалинской области'), ('Адвокатская палата Хабаровского края', 'Адвокатская палата Хабаровского края'), ('Адвокатская палата Чукотского автономного округа', 'Адвокатская палата Чукотского автономного округа'), ('Адвокатская палата Кировской области', 'Адвокатская палата Кировской области'), ('Адвокатская палата Оренбургской области', 'Адвокатская палата Оренбургской области'), ('Адвокатская палата Пензенской области', 'Адвокатская палата Пензенской области'), ('Адвокатская палата Пермского края', 'Адвокатская палата Пермского края'), ('Адвокатская палата Республики Башкортостан', 'Адвокатская палата Республики Башкортостан'), ('Адвокатская палата Республики Марий Эл', 'Адвокатская палата Республики Марий Эл'), ('Адвокатская палата Республики Мордовии', 'Адвокатская палата Республики Мордовии'), ('Адвокатская палата Республики Татарстан', 'Адвокатская палата Республики Татарстан'), ('Адвокатская палата Саратовской области', 'Адвокатская палата Саратовской области'), ('Адвокатская палата Удмуртской Республики', 'Адвокатская палата Удмуртской Республики'), ('Адвокатская палата Ульяновской области', 'Адвокатская палата Ульяновской области'), ('Адвокатская палата Чувашской Республики', 'Адвокатская палата Чувашской Республики'), ('Палата адвокатов Нижегородской области', 'Палата адвокатов Нижегородской области'), ('Палата адвокатов Самарской области', 'Палата адвокатов Самарской области'), ('Адвокатская палата Архангельской области', 'Адвокатская палата Архангельской области'), ('Адвокатская палата Вологодской области', 'Адвокатская палата Вологодской области'), ('Адвокатская палата г. Санкт-Петербурга', 'Адвокатская палата г. Санкт-Петербурга'), ('Адвокатская палата Калининградской области', 'Адвокатская палата Калининградской области'), ('Адвокатская палата Ленинградской области', 'Адвокатская палата Ленинградской области'), ('Адвокатская палата Мурманской области', 'Адвокатская палата Мурманской области'), ('Адвокатская палата Ненецкого автономного округа', 'Адвокатская палата Ненецкого автономного округа'), ('Адвокатская палата Псковской области', 'Адвокатская палата Псковской области'), ('Адвокатская палата Республики Карелия', 'Адвокатская палата Республики Карелия'), ('Адвокатская палата Республики Коми', 'Адвокатская палата Республики Коми'), ('Палата адвокатов Новгородской области', 'Палата адвокатов Новгородской области'), ('Адвокатская палата Ингушской Республики', 'Адвокатская палата Ингушской Республики'), ('Адвокатская палата Кабардино-Балкарской Республики', 'Адвокатская палата Кабардино-Балкарской Республики'), ('Адвокатская палата Карачаево-Черкесской Республики', 'Адвокатская палата Карачаево-Черкесской Республики'), ('Адвокатская палата Республики Дагестан', 'Адвокатская палата Республики Дагестан'), ('Адвокатская палата РСО — Алания', 'Адвокатская палата РСО — Алания'), ('Адвокатская палата Ставропольского края\t', 'Адвокатская палата Ставропольского края\t'), ('Адвокатская палата Чеченской Республики', 'Адвокатская палата Чеченской Республики'), ('Адвокатская палата Алтайского края', 'Адвокатская палата Алтайского края'), ('Адвокатская палата Забайкальского края', 'Адвокатская палата Забайкальского края'), ('Адвокатская палата Иркутской области', 'Адвокатская палата Иркутской области'), ('Адвокатская палата Кемеровской области', 'Адвокатская палата Кемеровской области'), ('Адвокатская палата Красноярского края', 'Адвокатская палата Красноярского края'), ('Адвокатская палата Новосибирской области', 'Адвокатская палата Новосибирской области'), ('Адвокатская палата Омской области', 'Адвокатская палата Омской области'), ('Адвокатская палата Республики Алтай', 'Адвокатская палата Республики Алтай'), ('Адвокатская палата Республики Бурятия', 'Адвокатская палата Республики Бурятия'), ('Адвокатская палата Республики Тыва', 'Адвокатская палата Республики Тыва'), ('Адвокатская палата Республики Хакасия', 'Адвокатская палата Республики Хакасия'), ('Адвокатская палата Томской области', 'Адвокатская палата Томской области'), ('Адвокатская палата Курганской области', 'Адвокатская палата Курганской области'), ('Адвокатская палата Свердловской области', 'Адвокатская палата Свердловской области'), ('Адвокатская палата Тюменской области', 'Адвокатская палата Тюменской области'), ('Адвокатская палата Ханты-Мансийского автономного округа', 'Адвокатская палата Ханты-Мансийского автономного округа'), ('Адвокатская палата Челябинской области', 'Адвокатская палата Челябинской области'), ('Адвокатская палата Ямало-Ненецкого автономного округа', 'Адвокатская палата Ямало-Ненецкого автономного округа'), ('Адвокатская палата Белгородской области', 'Адвокатская палата Белгородской области'), ('Адвокатская палата Брянской области', 'Адвокатская палата Брянской области'), ('Адвокатская палата Владимирской области', 'Адвокатская палата Владимирской области'), ('Адвокатская палата Воронежской области', 'Адвокатская палата Воронежской области'), ('Адвокатская палата г. Москвы', 'Адвокатская палата г. Москвы'), ('Адвокатская палата Ивановской области', 'Адвокатская палата Ивановской области'), ('Адвокатская палата Калужской области', 'Адвокатская палата Калужской области'), ('Адвокатская палата Костромской области', 'Адвокатская палата Костромской области'), ('Адвокатская палата Курской области', 'Адвокатская палата Курской области'), ('Адвокатская палата Липецкой области', 'Адвокатская палата Липецкой области'), ('Адвокатская палата Московской области', 'Адвокатская палата Московской области'), ('Адвокатская палата Орловской области', 'Адвокатская палата Орловской области'), ('Адвокатская палата Рязанской области', 'Адвокатская палата Рязанской области'), ('Адвокатская палата Смоленской области', 'Адвокатская палата Смоленской области'), ('Адвокатская палата Тамбовской области', 'Адвокатская палата Тамбовской области'), ('Адвокатская палата Тверской области', 'Адвокатская палата Тверской области'), ('Адвокатская палата Тульской области', 'Адвокатская палата Тульской области'), ('Адвокатская палата Ярославской области', 'Адвокатская палата Ярославской области'), ('Адвокатская палата Астраханской области', 'Адвокатская палата Астраханской области'), ('Адвокатская палата Волгоградской области', 'Адвокатская палата Волгоградской области'), ('Адвокатская палата Краснодарского края', 'Адвокатская палата Краснодарского края'), ('Адвокатская палата Республики Адыгея', 'Адвокатская палата Республики Адыгея'), ('Адвокатская палата Республики Калмыкия- Хальмг Тангч', 'Адвокатская палата Республики Калмыкия- Хальмг Тангч'), ('Адвокатская палата Ростовской области', 'Адвокатская палата Ростовской области')], max_length=100, null=True, verbose_name='Адвокатская палата'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='certificates_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер удостоверения'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='civil_law',
            field=models.BooleanField(default=False, verbose_name='Гражданское право'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='criminal_law',
            field=models.BooleanField(default=False, verbose_name='Уголовное право'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='date_of_issue_certificates',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи удостоверения'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='experience_in_civil_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в гражданском праве'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='experience_in_criminal_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в уголовном праве'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='experience_in_family_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в семейном праве'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='experience_in_housing_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в жилищном праве'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='experience_in_labour_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в трудовом праве'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='experience_in_municipal_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в муниципальном праве'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='experience_in_tax_law',
            field=models.DateField(blank=True, null=True, verbose_name='Опыт в налоговом праве'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='family_law',
            field=models.BooleanField(default=False, verbose_name='Семейное право'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='housing_law',
            field=models.BooleanField(default=False, verbose_name='Жилищное право'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='labour_law',
            field=models.BooleanField(default=False, verbose_name='Трудовое право'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='municipal_law',
            field=models.BooleanField(default=False, verbose_name='Муниципальное право'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='name_of_the_bar_association',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование адвокатского образования'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='payment_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Регистрационный номер'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='servicing_bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Обслуживающий банк'),
        ),
        migrations.AddField(
            model_name='memberofthebarchamber',
            name='tax_law',
            field=models.BooleanField(default=False, verbose_name='Налоговое право'),
        ),
    ]
